{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [04/Mar/2021 21:40:57] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "[2021-03-04 21:41:03,861] ERROR in app: Exception on /api/v1.0/start_date [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "TypeError: st() got an unexpected keyword argument 'start_date'\n",
      "127.0.0.1 - - [04/Mar/2021 21:41:03] \"\u001b[35m\u001b[1mGET /api/v1.0/start_date HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [04/Mar/2021 21:41:11] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [04/Mar/2021 21:41:25] \"\u001b[37mGET /api/v1.0/precipitation HTTP/1.1\u001b[0m\" 200 -\n",
      "[2021-03-04 21:41:31,659] ERROR in app: Exception on /api/v1.0/tobs [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1204, in _execute_context\n",
      "    context = constructor(dialect, self, conn, *args)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 806, in _init_compiled\n",
      "    self.cursor = self.create_cursor()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 1162, in create_cursor\n",
      "    return self._dbapi_connection.cursor()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 1000, in cursor\n",
      "    return self.connection.cursor(*args, **kwargs)\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 22848 and this is thread id 18504.\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-11b7569b600c>\", line 75, in tobs\n",
      "    temp = session.query(Measurement.date, Measurement.tobs).filter(Measurement.station == 'USC00519281').filter(Measurement.date >= last_year).all()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\orm\\query.py\", line 3373, in all\n",
      "    return list(self)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\orm\\query.py\", line 3535, in __iter__\n",
      "    return self._execute_and_instances(context)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\orm\\query.py\", line 3560, in _execute_and_instances\n",
      "    result = conn.execute(querycontext.statement, self._params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1011, in execute\n",
      "    return meth(self, multiparams, params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\sql\\elements.py\", line 298, in _execute_on_connection\n",
      "    return connection._execute_clauseelement(self, multiparams, params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1130, in _execute_clauseelement\n",
      "    distilled_params,\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1207, in _execute_context\n",
      "    e, util.text_type(statement), parameters, None, None\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1511, in _handle_dbapi_exception\n",
      "    sqlalchemy_exception, with_traceback=exc_info[2], from_=e\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\util\\compat.py\", line 182, in raise_\n",
      "    raise exception\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1204, in _execute_context\n",
      "    context = constructor(dialect, self, conn, *args)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 806, in _init_compiled\n",
      "    self.cursor = self.create_cursor()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 1162, in create_cursor\n",
      "    return self._dbapi_connection.cursor()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 1000, in cursor\n",
      "    return self.connection.cursor(*args, **kwargs)\n",
      "sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 22848 and this is thread id 18504.\n",
      "[SQL: SELECT measurement.date AS measurement_date, measurement.tobs AS measurement_tobs \n",
      "FROM measurement \n",
      "WHERE measurement.station = ? AND measurement.date >= ?]\n",
      "[parameters: [immutabledict({})]]\n",
      "(Background on this error at: http://sqlalche.me/e/13/f405)\n",
      "127.0.0.1 - - [04/Mar/2021 21:41:31] \"\u001b[35m\u001b[1mGET /api/v1.0/tobs HTTP/1.1\u001b[0m\" 500 -\n",
      "[2021-03-04 21:41:35,022] ERROR in app: Exception on /api/v1.0/tobs [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1204, in _execute_context\n",
      "    context = constructor(dialect, self, conn, *args)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 806, in _init_compiled\n",
      "    self.cursor = self.create_cursor()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 1162, in create_cursor\n",
      "    return self._dbapi_connection.cursor()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 1000, in cursor\n",
      "    return self.connection.cursor(*args, **kwargs)\n",
      "sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 22848 and this is thread id 13948.\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"<ipython-input-1-11b7569b600c>\", line 75, in tobs\n",
      "    temp = session.query(Measurement.date, Measurement.tobs).filter(Measurement.station == 'USC00519281').filter(Measurement.date >= last_year).all()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\orm\\query.py\", line 3373, in all\n",
      "    return list(self)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\orm\\query.py\", line 3535, in __iter__\n",
      "    return self._execute_and_instances(context)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\orm\\query.py\", line 3560, in _execute_and_instances\n",
      "    result = conn.execute(querycontext.statement, self._params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1011, in execute\n",
      "    return meth(self, multiparams, params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\sql\\elements.py\", line 298, in _execute_on_connection\n",
      "    return connection._execute_clauseelement(self, multiparams, params)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1130, in _execute_clauseelement\n",
      "    distilled_params,\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1207, in _execute_context\n",
      "    e, util.text_type(statement), parameters, None, None\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1511, in _handle_dbapi_exception\n",
      "    sqlalchemy_exception, with_traceback=exc_info[2], from_=e\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\util\\compat.py\", line 182, in raise_\n",
      "    raise exception\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 1204, in _execute_context\n",
      "    context = constructor(dialect, self, conn, *args)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 806, in _init_compiled\n",
      "    self.cursor = self.create_cursor()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 1162, in create_cursor\n",
      "    return self._dbapi_connection.cursor()\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\class_31\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 1000, in cursor\n",
      "    return self.connection.cursor(*args, **kwargs)\n",
      "sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 22848 and this is thread id 13948.\n",
      "[SQL: SELECT measurement.date AS measurement_date, measurement.tobs AS measurement_tobs \n",
      "FROM measurement \n",
      "WHERE measurement.station = ? AND measurement.date >= ?]\n",
      "[parameters: [immutabledict({})]]\n",
      "(Background on this error at: http://sqlalche.me/e/13/f405)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [04/Mar/2021 21:41:35] \"\u001b[35m\u001b[1mGET /api/v1.0/tobs HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask, jsonify, render_template\n",
    "\n",
    "import datetime as dt\n",
    "\n",
    "import sqlalchemy\n",
    "from sqlalchemy.ext.automap import automap_base\n",
    "from sqlalchemy.orm import Session\n",
    "from sqlalchemy import create_engine, func\n",
    "\n",
    "import numpy as np\n",
    "import json\n",
    "import pandas as pd\n",
    "\n",
    "# Create egine for database connection\n",
    "sql = \"sqlite:///Resources/hawaii.sqlite\"\n",
    "engine = create_engine(sql, pool_pre_ping=True)\n",
    "\n",
    "# Create autmap_base \n",
    "Base = automap_base()\n",
    "# Reflect database tables\n",
    "Base.prepare(engine, reflect=True)\n",
    "\n",
    "# Save references to each table\n",
    "Measurement = Base.classes.measurement\n",
    "Station = Base.classes.station\n",
    "\n",
    "session = Session(engine)\n",
    "\n",
    "# Setup Flask\n",
    "\n",
    "app = Flask(__name__)\n",
    "\n",
    "# Create initital route with route's summary\n",
    "@app.route(\"/\")\n",
    "def welcome():\n",
    "    return (\n",
    "        f\"Welcome to the Hawaii Weather API!<br/>\"\n",
    "        f\"Available Routes:<br/>\"\n",
    "        f\"/api/v1.0/precipitation<br/>\"\n",
    "        f\"/api/v1.0/stations<br/>\"\n",
    "        f\"/api/v1.0/tobs<br/>\"\n",
    "        f\"/api/v1.0/start_date<br/>\"\n",
    "        f\"/api/v1.0/start_date/end_date<br/>\"\n",
    "        f\"Please enter date as yyyy-mm-dd\")\n",
    "    \n",
    "# Create an app route to returning date and percipitation data in JSON format\n",
    "\n",
    "@app.route(\"/api/v1.0/precipitation\")\n",
    "def preci():\n",
    "    \"\"\"Return Percipitation Data - 1 year\"\"\"\n",
    "    # Create a variable to filter only the last year of analysis\n",
    "    last_year = dt.date(2017, 8, 23) - dt.timedelta(days=365)\n",
    "    # Query for the date and precipitation for the last year\n",
    "    rainfall = session.query(Measurement.date, Measurement.prcp).filter(Measurement.date >= last_year).all()\n",
    "    # Transform our query into a list\n",
    "    rain = list(np.ravel(rainfall))\n",
    "    # Return the data in json format\n",
    "    return jsonify(rain=rain)\n",
    "\n",
    "@app.route(\"/api/v1.0/stations\")\n",
    "def stations():\n",
    "    \"\"\"List of stations.\"\"\"\n",
    "    # Query the name of each station in our DB\n",
    "    stat = session.query(Station.station).all()\n",
    "    # Transform our query into a list\n",
    "    station_list = list(np.ravel(stat))\n",
    "    # Return the data in json format\n",
    "    return jsonify(station_list=station_list)\n",
    "\n",
    "@app.route(\"/api/v1.0/tobs\")\n",
    "def tobs():\n",
    "    # Create a variable to filter only the last year of analysis\n",
    "    last_year = dt.date(2017, 8, 23) - dt.timedelta(days=365)\n",
    "    \n",
    "    temp = session.query(Measurement.date, Measurement.tobs).filter(Measurement.station == 'USC00519281').filter(Measurement.date >= last_year).all()\n",
    "    \n",
    "    tobs_list = list(np.ravel(temp))\n",
    "    \n",
    "    return jsonify(tobs_list=tobs_list)\n",
    "\n",
    "@app.route(\"/api/v1.0/<start_date>\")\n",
    "def st(start=None):\n",
    "    \n",
    "    start_temp = session.query(func.min(Measurement.tobs),func.avg(Measurement.tobs),func.max(Measurement.tobs)).filter(Measurement.date >= start).all()\n",
    "\n",
    "    start_list = list(np.ravel(start_temp))\n",
    "    \n",
    "    return jsonify(start_list=start_list)\n",
    "\n",
    "@app.route(\"/api/v1.0/<start_date>/<end_date>\")\n",
    "def st_end(start=None ,end=None):\n",
    "    \n",
    "    min_max = session.query(func.min(Measurement.tobs),func.avg(Measurement.tobs),func.max(Measurement.tobs)).filter(Measurement.date >= start, Measurement.date <= end).all()\n",
    "\n",
    "    min_max_list = list(np.ravel(min_max))\n",
    "    \n",
    "    return jsonify(min_max_list=min_max_list)\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.9"
  },
  "varInspector": {
   "cols": {
    "lenName": 16,
    "lenType": 16,
    "lenVar": 40
   },
   "kernels_config": {
    "python": {
     "delete_cmd_postfix": "",
     "delete_cmd_prefix": "del ",
     "library": "var_list.py",
     "varRefreshCmd": "print(var_dic_list())"
    },
    "r": {
     "delete_cmd_postfix": ") ",
     "delete_cmd_prefix": "rm(",
     "library": "var_list.r",
     "varRefreshCmd": "cat(var_dic_list()) "
    }
   },
   "types_to_exclude": [
    "module",
    "function",
    "builtin_function_or_method",
    "instance",
    "_Feature"
   ],
   "window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
